name: CI

on:
  - push
  - pull_request

jobs:
  ###
  # ANALYSE
  ###

  analyse:
    name: Analyse

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - uses: actions/setup-go@v3.5.0
        with:
          go-version-file: ./go.mod
          cache: true

      - run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: latest
          install-go: false
          cache-key: "${{ matrix.go }}"

  ###
  # TEST
  ###

  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - uses: actions/setup-go@v3.5.0
        with:
          go-version-file: ./go.mod
          cache: true

      - run: go test ./...

  ###
  # Build
  ###

  build:
    name: Build

    needs:
      - analyse
      - test

    # We don't need to build on anything other than Ubuntu, as the final
    # builds will end up being done in Github Actions.
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3.5.0
        with:
          go-version-file: ./go.mod
          cache: true

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot --clean
